- name: apt | add mongodb repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EA312927
    state: present
  tags:
    - mongodb_apt-install-packages

- name: apt | add Ubuntu repo
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/{{ mongodb_version }} multiverse"
    state: present
  when: ansible_distribution == 'Ubuntu'
  tags:
    - mongodb_apt-install-packages

- name: apt | add Debian repo
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/{{ mongodb_version }} main"
    state: present
  when: ansible_distribution == 'Debian'
  tags:
    - mongodb_apt-install-packages

- name: apt | install mongodb packages
  apt:
    name: mongodb-org
    state: present
  tags:
    - mongodb_apt-install-packages
